/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */

// This is a guard condition so that contents of this file are not included
// more than once.  
#pragma once

#include <xc.h> // include processor files - each processor file is guarded.  

#define T0CS_T0CKI (uint8_t)0x20
#define T0CS_INTERNAL_INSTRUCTION_CYCLE_CLOCK (uint8_t)0x00
#define T0SE_INCREMENT_HIGH_TO_LOW_T0CKI (uint8_t)0x10
#define T0SE_INCREMENT_LOW_TO_HIGH_T0CKI (uint8_t)0x00
#define TMR0_PS_1_2 (uint8_t)0x00
#define TMR0_PS_1_4 (uint8_t)0x01
#define TMR0_PS_1_8 (uint8_t)0x02
#define TMR0_PS_1_16 (uint8_t)0x03
#define TMR0_PS_1_32 (uint8_t)0x04
#define TMR0_PS_1_64 (uint8_t)0x05
#define TMR0_PS_1_128 (uint8_t)0x06
#define TMR0_PS_1_256 (uint8_t)0x07

#define RELOAD_TMR0 (uint8_t)100 // 9.984msec

void TMR0Initialize(void);
