/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */

// This is a guard condition so that contents of this file are not included
// more than once.  
#ifndef TMR1_H
#define	TMR1_H

#include <xc.h> // include processor files - each processor file is guarded.  

#define TMR1_T1CKPS_1_8 (uint8_t)0x30
#define TMR1_T1CKPS_1_4 (uint8_t)0x20
#define TMR1_T1CKPS_1_2 (uint8_t)0x10
#define TMR1_T1CKPS_1_1 (uint8_t)0x00
#define TMR1_T1OSCEN_ENABLE (uint8_t)0x06
#define TMR1_T1OSCEN_DISABLE (uint8_t)0x00
#define TMR1_T1SYNC_ENABLE (uint8_t)0x00
#define TMR1_T1SYNC_DISABLE (uint8_t)0x04
#define TMR1_TMR1CS_T1CKI (uint8_t)0x02
#define TMR1_TMR1CS_FOSC4 (uint8_t)0x00
#define TMR1_TMR1ON_ON (uint8_t)0x01
#define TMR1_TMR1ON_OFF (uint8_t)0x00

#define RELOAD_TMR1_H (uint8_t)0x00
#define RELOAD_TMR1_L (uint8_t)0x00


void TMR1Initialize(void);
void TMR1Start(void);
void TMR1Stop(void);
void TMR1Reset(void);

#endif	/* TMR1_H */

